/*
 * Irresistible Gaming (c) 2018
 * Developed by Lorenc_
 * Module: colors.inc
 * Purpose: colors and its functions
 */

/* ** Colours ** */
#define COL_GREEN               	"{6EF83C}"
#define COL_RED                 	"{F81414}"
#define COL_BLUE		           	"{00C0FF}"
#define COL_GOLD                	"{FFDC2E}"
#define COL_GREY                    "{C0C0C0}"
#define COL_PINK                    "{FF0770}"
#define COL_WHITE                   "{FFFFFF}"
#define COL_ORANGE                  "{FF7500}"
#define COL_YELLOW                  "{FFFF00}"
#define COL_BLACK					"{333333}"
#define COLOR_GREEN             	0x00CC00FF
#define COLOR_RED               	0xFF0000FF
#define COLOR_BLUE                  0x00C0FFFF
#define COLOR_YELLOW            	0xFFFF00FF
#define COLOR_ORANGE            	0xEE9911FF
#define COLOR_GREY                  0xC0C0C0FF
#define COLOR_WHITE                 0xFFFFFFFF
#define COLOR_PINK                  0xFF0770FF
#define COLOR_GOLD                  0xFFDC2EFF
